_target_: src.models.ssc_module.SSCLitModule

net:
  _target_: src.models.components.RWKVPCSSC.PCSSC
  class_num: 19
  dim_feat: 1024
  num_p0: 53248
  num_pin: 26624
  radius: 100
  up_factors: [ 4 ]
  grid_size: [ 0.02, 0.01 ]
  hidden_dim: 128

loss:
  _target_: src.loss.ssc_loss_nofps.Loss
  seg_weight: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
  sqrt: True
  ratio: [1e2, 1e1]
  use_fps: False
  threshold: 0.3
optimizer:
  _target_: torch.optim.Adamax
  _partial_: true
  lr: 0.003
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 1e-4
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 1
  gamma: 0.9
  last_epoch: -1

dataset: V2XSeqSPD-scene-split

class_num: 18
